### ISSUE TITLE
use conda enironment description

### ISSUE THREAD

**Issue by mkuzak** [sara-nl/spicercourse#2]
It's a suggestion to replace installing tools one by one with use of the environment.yml, that captures all requirements.

**Comment by maithili-k** [comment]
We thought of doing it in one go, but wanted the participants to go through each of the tools so they see how it is done (and for those who find it intimidating can see that it is not that hard), and it feels more interactive. And again like you said that it also feels a bit tedious so they see the point of having a software manager.
