### ISSUE TITLE
not clear what the learner is supposed to do when editing the `.bashrc` file

### ISSUE THREAD

**Issue by mkuzak** [sara-nl/spicercourse#4]
in `singularity-usage.md` it is not clear what the learner is supposed to do when editing the `.bashrc` file. It says nano `.bashrc` but the text is different than the content of the .bashrc file. It says *uncomment* but in the brackets it says *"add #"* which means comment out.
It would be clearer to state *"comment out lines between # >>> conda initialize >>> statements"*
or instead commenting out `.bashrc` file, deactivate conda environment by runing `conda deactivate`

**Comment by maithili-k** [comment]
thanks, have changed the description
